#:schema ../schemas/latest.json

out_dir = "tests/output"

vars = { my_var = 15 }

templates = { lit_template = "my_var: {{ my_var }}", cmd_template = "echo \"engine feels good, much {{ condition }} than before... amazing\" > output_from_template_id.txt" }

templates_dir = "tests/templates"

[typescript]
catalog = true

pnpm.packages = ["packages"]

[typescript.package_presets.test]
name = "test_package"
package_json = "extended"
dir = "packages/test_package"

[typescript.people]
Aragorn = { name = "Aragorn", email = "aragorn@middleeath.com", url = "aragorn.middleearth.com" }
Legolas = { name = "Legolas", email = "legolas@middleeath.com", url = "legolas.middleearth.com" }

[typescript.package_json_presets.base]
keywords = ["hobbits", "isengard"]
bugs = { url = "hobbits.com", email = "hello@hobbits.com" }
author = { name = "Frodo", email = "Frodo@hobbits.com", url = "hobbits.com" }

[typescript.package_json_presets.extended]
extends = ["base"]
contributors = ["Aragorn", "Legolas"]
maintainers = ["Aragorn", "Legolas"]

[typescript.package_json_presets.app]
dev_dependencies = { svelte = "latest", tailwindcss = "catalog:", "@sveltejs/kit" = "catalog:svelte" }
