use std::{collections::BTreeSet, sync::LazyLock};

use maplit::btreeset;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use super::{PreCommitHook, Repo};

pub(crate) static GITLEAKS_REPO: LazyLock<Repo> = LazyLock::new(|| Repo::Uri {
	repo: "https://github.com/gitleaks/gitleaks".to_string(),
	rev: Some("v8.28.0".to_string()),
	hooks: btreeset! { PreCommitHook { id: "gitleaks".to_string(), ..Default::default() } },
});

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, JsonSchema, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum Language {
	Conda,
	Coursier,
	Dart,
	Docker,
	DockerImage,
	Dotnet,
	Fail,
	Golang,
	Lua,
	Node,
	Perl,
	Python,
	PythonVenv,
	R,
	Ruby,
	Rust,
	Swift,
	Pygrep,
	Script,
	System,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, JsonSchema, Eq, PartialOrd, Ord)]
#[serde(rename_all = "kebab-case")]
pub enum Stage {
	Commit,
	MergeCommit,
	Push,
	PrepareCommitMsg,
	CommitMsg,
	PostCheckout,
	PostCommit,
	PostMerge,
	PostRewrite,
	PreCommit,
	PreMergeCommit,
	PrePush,
	PreRebase,
	Manual,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, JsonSchema, PartialOrd, Ord, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum FileType {
	AdobeIllustrator,
	Alpm,
	Apinotes,
	Asar,
	Asciidor,
	Ash,
	Asm,
	Aspectj,
	Audio,
	Avif,
	Awk,
	Babelrc,
	Bash,
	Batch,
	Bats,
	Bazel,
	Bazelrc,
	Bib,
	Binary,
	Bitmap,
	Bowerrc,
	Browserslistrc,
	Bzip2,
	C,
	#[serde(rename = "c#")]
	CSharp,
	#[serde(rename = "c++")]
	#[allow(clippy::upper_case_acronyms)]
	CPP,
	C2hd,
	Cbsd,
	Clojure,
	Clojurescript,
	Cmake,
	Codespellrc,
	Coffee,
	Coveragerc,
	Crystal,
	Csh,
	Cson,
	Csproj,
	Css,
	Csslintrc,
	Csv,
	Cuda,
	Cython,
	Dart,
	Dash,
	Def,
	Diff,
	Directory,
	Dockerfile,
	Dotenv,
	Dtd,
	EditorConfig,
	Edn,
	Ejs,
	Eot,
	Eps,
	Erb,
	Executable,
	Expect,
	File,
	Fish,
	Flake8,
	Gdscript,
	Geojson,
	Gherkin,
	Gif,
	Gitattributes,
	Gitconfig,
	Gitignore,
	Gitlint,
	Gitmodules,
	Go,
	GoMod,
	GoSum,
	Gotimpl,
	Gpx,
	Graphql,
	Gyb,
	Gyp,
	Gzip,
	Handlebars,
	Haskell,
	Hcl,
	Header,
	Hgrc,
	Html,
	Icalendar,
	Icns,
	Icon,
	Idl,
	Idris,
	Image,
	Inc,
	Ini,
	Inl,
	Ino,
	Inx,
	Jade,
	Jar,
	Java,
	JavaProperties,
	Javascript,
	Jenkins,
	Jinja,
	Jpeg,
	Jshintrc,
	Json,
	Json5,
	Jsonnet,
	Jsx,
	Jupyter,
	Kml,
	Kotlin,
	Ksh,
	Lean,
	Lektor,
	Lektorproject,
	Less,
	Liquid,
	LiterateHaskell,
	Lua,
	Mailmap,
	Makefile,
	Manifest,
	Map,
	Markdown,
	Mdx,
	MentionBot,
	Meson,
	Mib,
	Modulemap,
	Musescore,
	Myst,
	Ngdoc,
	Nim,
	Nimble,
	Nix,
	NonExecutable,
	Npmignore,
	Nunjucks,
	ObjectiveC,
	#[serde(rename = "objective-c++")]
	ObjectiveCPP,
	Ocaml,
	Otf,
	P12,
	Pdbrc,
	Pdf,
	Pem,
	Perl,
	Php,
	Pkgbuild,
	PlainText,
	Plantuml,
	Plist,
	Png,
	Pofile,
	Powershell,
	Prettierignore,
	Prisma,
	Proto,
	Puppet,
	Purescript,
	Pyi,
	Pylintrc,
	Pypirc,
	Pyproj,
	Python,
	Python2,
	Python3,
	Pyz,
	Qml,
	R,
	RelaxNg,
	Rst,
	Ruby,
	Rust,
	Salt,
	Sass,
	Sbt,
	Scala,
	Scheme,
	Scss,
	Sh,
	Shell,
	Sln,
	Socket,
	Solidity,
	Spec,
	Sql,
	Stylus,
	Svelte,
	Svg,
	Swf,
	Swift,
	Swiftdeps,
	Symlink,
	SystemVerilog,
	Tar,
	Tcsh,
	Terraform,
	Tex,
	Text,
	Thrift,
	Tiff,
	Toml,
	Ts,
	Tsv,
	Tsx,
	Ttf,
	Twig,
	Twisted,
	Tsxprofile,
	Urdf,
	Vb,
	Vbproj,
	Vcxproj,
	Vdx,
	Verilog,
	Vhdl,
	Vim,
	Vtl,
	Vue,
	Wav,
	Webp,
	Wheel,
	Wky,
	Woff,
	Woff2,
	Wsgi,
	Xhtml,
	Xml,
	Xquery,
	Xsd,
	Xsl,
	Yaml,
	Yamllint,
	Yang,
	Yin,
	Zcml,
	Zig,
	Zip,
	Zpt,
	Zsh,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum AutoUpdateSchedule {
	Weekly,
	Monthly,
	Quarterly,
}

/// pre-commit.ci specific settings https://pre-commit.ci/#configuration
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, JsonSchema, Default)]
#[serde(default)]
pub struct CiSettings {
	/// A commit message for pull request autofixes https://pre-commit.ci/#configuration
	#[serde(skip_serializing_if = "Option::is_none")]
	pub autofix_commit_msg: Option<String>,

	/// Whether to autofix pull requests https://pre-commit.ci/#configuration
	#[serde(skip_serializing_if = "Option::is_none")]
	pub autofix_prs: Option<bool>,

	/// A branch to send pull request's autoupdate to https://pre-commit.ci/#configuration
	#[serde(skip_serializing_if = "Option::is_none")]
	pub autoupdate_branch: Option<String>,

	/// A commit message for autoupdate pull requests https://pre-commit.ci/#configuration
	#[serde(skip_serializing_if = "Option::is_none")]
	pub autoupdate_commit_msg: Option<String>,

	/// An autoupdate frequency https://pre-commit.ci/#configuration
	#[serde(skip_serializing_if = "Option::is_none")]
	pub autoupdate_schedule: Option<AutoUpdateSchedule>,

	/// List of skipped hook's ids https://pre-commit.ci/#configuration
	#[serde(skip_serializing_if = "Option::is_none")]
	pub skip: Option<BTreeSet<String>>,

	/// Whether to recursively check out submodules https://pre-commit.ci/#configuration
	#[serde(skip_serializing_if = "Option::is_none")]
	pub submodules: Option<bool>,
}
